<?php
echo "\n"; 
echo "<head>\n"; 
echo "    <meta charset=\"UTF-8\">\n"; 
echo "    <meta name=\"description\" content=\"Sayur Template\">\n"; 
echo "    <meta name=\"keywords\" content=\"Sayur, unica, creative, html\">\n"; 
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"; 
echo "    <meta http-equiv=\"X-UABebas Biaya Pengiriman-Compatible\" content=\"ie=edge\">\n"; 
echo "    <title>BajakSayur.co</title>\n"; 
echo "\n"; 
echo "    <!-- Google Font -->\n"; 
echo "    <link href=\"https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap\" rel=\"stylesheet\">\n"; 
echo "\n"; 
echo "    <!-- Css Styles -->\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" type=\"text/css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/elegant-icons.css\" type=\"text/css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/nice-select.css\" type=\"text/css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/jquery-ui.min.css\" type=\"text/css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\" type=\"text/css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/slicknav.min.css\" type=\"text/css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body>\n"; 
echo "    <!-- Page Preloder -->\n"; 
echo "    <div id=\"preloder\">\n"; 
echo "        <div class=\"loader\"></div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- Humberger Begin -->\n"; 
echo "    <div class=\"humberger__menu__overlay\"></div>\n"; 
echo "    <div class=\"humberger__menu__wrapper\">\n"; 
echo "        <div class=\"humberger__menu__logo\">\n"; 
echo "            <a href=\"#\"><img src=\"img/logo.png\" alt=\"\"></a>\n"; 
echo "        </div>\n"; 
echo "        <div class=\"humberger__menu__cart\">\n"; 
echo "            <ul>\n"; 
echo "                <li><a href=\"#\"><i class=\"fa fa-heart\"></i> <span>1</span></a></li>\n"; 
echo "                <li><a href=\"#\"><i class=\"fa fa-shopping-bag\"></i> <span>3</span></a></li>\n"; 
echo "            </ul>\n"; 
echo "            <div class=\"header__cart__price\">item: <span>Rp:150.000,-</span></div>\n"; 
echo "        </div>\n"; 
echo "        <div class=\"humberger__menu__widget\">\n"; 
echo "            <div class=\"header__top__right__language\">\n"; 
echo "                <img src=\"img/language.png\" alt=\"\">\n"; 
echo "                   <div>Indonesia</div>\n"; 
echo "            </div>\n"; 
echo "            <div class=\"header__top__right__auth\">\n"; 
echo "                <a href=\"#\"><i class=\"fa fa-user\"></i> Login</a>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "        <nav class=\"humberger__menu__nav mobile-menu\">\n"; 
echo "            <ul>\n"; 
echo "                <li class=\"active\"><a href=\"3\">Home</a></li>\n"; 
echo "                <li><a href=\"#\">Shop</a></li>\n"; 
echo "                <li><a href=\"#\">Blog Details</a></li>\n"; 
echo "                <li><a href=\"#\">Contact</a></li>\n"; 
echo "            </ul>\n"; 
echo "        </nav>\n"; 
echo "        <div id=\"mobile-menu-wrap\"></div>\n"; 
echo "        <div class=\"header__top__right__social\">\n"; 
echo "            <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n"; 
echo "            <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n"; 
echo "            <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "            <a href=\"#\"><i class=\"fa fa-pinterest-p\"></i></a>\n"; 
echo "        </div>\n"; 
echo "        <div class=\"humberger__menu__contact\">\n"; 
echo "            <ul>\n"; 
echo "                <li><i class=\"fa fa-envelope\"></i>DPirates@gmail.com</li>\n"; 
echo "                <li>Bebas Biaya Pengiriman</li>\n"; 
echo "            </ul>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!-- Humberger End -->\n"; 
echo "\n"; 
echo "    <!-- Header Section Begin -->\n"; 
echo "    <header class=\"header\">\n"; 
echo "        <div class=\"header__top\">\n"; 
echo "            <div class=\"container\">\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-6 col-md-6\">\n"; 
echo "                        <div class=\"header__top__left\">\n"; 
echo "                            <ul>\n"; 
echo "                                <li><i class=\"fa fa-envelope\"></i>DPirates@gmail.com</li>\n"; 
echo "                                <li>Bebas Biaya Pengiriman</li>\n"; 
echo "                            </ul>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"col-lg-6 col-md-6\">\n"; 
echo "                        <div class=\"header__top__right\">\n"; 
echo "                            <div class=\"header__top__right__social\">\n"; 
echo "                                <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n"; 
echo "                                <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n"; 
echo "                                <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                                <a href=\"#\"><i class=\"fa fa-pinterest-p\"></i></a>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"header__top__right__language\">\n"; 
echo "                                <img src=\"img/language.png\" alt=\"\">\n"; 
echo "                                <div>Indonesia</div>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"header__top__right__auth\">\n"; 
echo "                                <a href=\"#\"><i class=\"fa fa-user\"></i> Login</a>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-3\">\n"; 
echo "                    <div class=\"header__logo\">\n"; 
echo "                        <a href=\"./index.html\"><img src=\"img/logo.png\" alt=\"\"></a>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-6\">\n"; 
echo "                    <nav class=\"header__menu\">\n"; 
echo "                        <ul>\n"; 
echo "                            <li class=\"active\"><a href=\"./index.html\">Home</a></li>\n"; 
echo "                            <li><a href=\"#\">Shop</a></li>\n"; 
echo "                        \n"; 
echo "                            <li><a href=\"#\">Blog</a></li>\n"; 
echo "                            <li><a href=\"#\">Contact</a></li>\n"; 
echo "                        </ul>\n"; 
echo "                    </nav>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-3\">\n"; 
echo "                    <div class=\"header__cart\">\n"; 
echo "                        <ul>\n"; 
echo "                            <li><a href=\"#\"><i class=\"fa fa-heart\"></i> <span>1</span></a></li>\n"; 
echo "                            <li><a href=\"#\"><i class=\"fa fa-shopping-bag\"></i> <span>3</span></a></li>\n"; 
echo "                        </ul>\n"; 
echo "                        <div class=\"header__cart__price\">item: <span>Rp:150.000,-</span></div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "            <div class=\"humberger__open\">\n"; 
echo "                <i class=\"fa fa-bars\"></i>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </header>\n"; 
echo "    <!-- Header Section End -->\n"; 
echo "\n"; 
echo "    <!-- Hero Section Begin -->\n"; 
echo "    <section class=\"hero\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-3\">\n"; 
echo "                    <div class=\"hero__categories\">\n"; 
echo "                        <div class=\"hero__categories__all\">\n"; 
echo "                            <i class=\"fa fa-bars\"></i>\n"; 
echo "                            <span>All departments</span>\n"; 
echo "                        </div>\n"; 
echo "                        <ul>\n"; 
echo "                            <li><a href=\"#\">Fresh Meat</a></li>\n"; 
echo "                            <li><a href=\"#\">Vegetables</a></li>\n"; 
echo "                            <li><a href=\"#\">Fruit & Nut Gifts</a></li>\n"; 
echo "                            <li><a href=\"#\">Fresh Berries</a></li>\n"; 
echo "                            <li><a href=\"#\">Ocean Foods</a></li>\n"; 
echo "                            <li><a href=\"#\">Butter & Eggs</a></li>\n"; 
echo "                            <li><a href=\"#\">Fastfood</a></li>\n"; 
echo "                            <li><a href=\"#\">Fresh Onion</a></li>\n"; 
echo "                            <li><a href=\"#\">Papayaya & Crisps</a></li>\n"; 
echo "                            <li><a href=\"#\">Oatmeal</a></li>\n"; 
echo "                            <li><a href=\"#\">Fresh Bananas</a></li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-9\">\n"; 
echo "                    <div class=\"hero__search\">\n"; 
echo "                        <div class=\"hero__search__form\">\n"; 
echo "                            <form action=\"#\">\n"; 
echo "                                <div class=\"hero__search__categories\">\n"; 
echo "                                    Categories\n"; 
echo "                                    <span class=\"arrow_carrot-down\"></span>\n"; 
echo "                                </div>\n"; 
echo "                                <input type=\"text\" placeholder=\"Apa yang kamu cari?\">\n"; 
echo "                                <button type=\"submit\" class=\"site-btn\">SEARCH</button>\n"; 
echo "                            </form>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"hero__search__phone\">\n"; 
echo "                            <div class=\"hero__search__phone__icon\">\n"; 
echo "                                <i class=\"fa fa-phone\"></i>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"hero__search__phone__text\">\n"; 
echo "                                <h5>+62 878 4207-7793</h5>\n"; 
echo "                                <span>Buka Setiap Hari</span>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"hero__item set-bg\" data-setbg=\"img/hero/banner.jpg\">\n"; 
echo "                        <div class=\"hero__text\">\n"; 
echo "                            <span>FRUIT FRESH</span>\n"; 
echo "                            <h2>Vegetable <br />100% Organic</h2>\n"; 
echo "                            <p>Gratis Pengiriman</p>\n"; 
echo "                            <a href=\"#\" class=\"primary-btn\">Langsung Pesan</a>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </section>\n"; 
echo "    <!-- Hero Section End -->\n"; 
echo "\n"; 
echo "    <!-- Categories Section Begin -->\n"; 
echo "    <section class=\"categories\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"categories__slider owl-carousel\">\n"; 
echo "                    <div class=\"col-lg-3\">\n"; 
echo "                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-1.jpg\">\n"; 
echo "                            <h5><a href=\"#\">Fresh Fruit</a></h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"col-lg-3\">\n"; 
echo "                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-2.jpg\">\n"; 
echo "                            <h5><a href=\"#\">Dried Fruit</a></h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"col-lg-3\">\n"; 
echo "                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-3.jpg\">\n"; 
echo "                            <h5><a href=\"#\">Vegetables</a></h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"col-lg-3\">\n"; 
echo "                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-4.jpg\">\n"; 
echo "                            <h5><a href=\"#\">drink fruits</a></h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"col-lg-3\">\n"; 
echo "                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-5.jpg\">\n"; 
echo "                            <h5><a href=\"#\">drink fruits</a></h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </section>\n"; 
echo "    <!-- Categories Section End -->\n"; 
echo "\n"; 
echo "    <!-- Featured Section Begin -->\n"; 
echo "    <section class=\"featured spad\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-12\">\n"; 
echo "                    <div class=\"section-title\">\n"; 
echo "                        <h2>Featured Product</h2>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"featured__controls\">\n"; 
echo "                        <ul>\n"; 
echo "                            <li class=\"active\" data-filter=\"*\">All</li>\n"; 
echo "                            <li data-filter=\".oranges\">Oranges</li>\n"; 
echo "                            <li data-filter=\".fresh-meat\">Fresh Meat</li>\n"; 
echo "                            <li data-filter=\".vegetables\">Vegetables</li>\n"; 
echo "                            <li data-filter=\".fastfood\">Fastfood</li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "            <div class=\"row featured__filter\">\n"; 
echo "                <div class=\"col-lg-3 col-md-4 col-sm-6 mix oranges fresh-meat\">\n"; 
echo "                    <div class=\"featured__item\">\n"; 
echo "                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-1.jpg\">\n"; 
echo "                            <ul class=\"featured__item__pic__hover\">\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\n"; 
echo "                            </ul>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"featured__item__text\">\n"; 
echo "                            <h6><a href=\"#\">Crab Pool Security</a></h6>\n"; 
echo "                            <h5>Rp35.000</h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-3 col-md-4 col-sm-6 mix vegetables fastfood\">\n"; 
echo "                    <div class=\"featured__item\">\n"; 
echo "                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-2.jpg\">\n"; 
echo "                            <ul class=\"featured__item__pic__hover\">\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\n"; 
echo "                            </ul>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"featured__item__text\">\n"; 
echo "                            <h6><a href=\"#\">Crab Pool Security</a></h6>\n"; 
echo "                            <h5>Rp35.000</h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-3 col-md-4 col-sm-6 mix vegetables fresh-meat\">\n"; 
echo "                    <div class=\"featured__item\">\n"; 
echo "                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-3.jpg\">\n"; 
echo "                            <ul class=\"featured__item__pic__hover\">\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\n"; 
echo "                            </ul>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"featured__item__text\">\n"; 
echo "                            <h6><a href=\"#\">Crab Pool Security</a></h6>\n"; 
echo "                            <h5>Rp35.000</h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-3 col-md-4 col-sm-6 mix fastfood oranges\">\n"; 
echo "                    <div class=\"featured__item\">\n"; 
echo "                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-4.jpg\">\n"; 
echo "                            <ul class=\"featured__item__pic__hover\">\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\n"; 
echo "                            </ul>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"featured__item__text\">\n"; 
echo "                            <h6><a href=\"#\">Crab Pool Security</a></h6>\n"; 
echo "                            <h5>Rp35.000</h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-3 col-md-4 col-sm-6 mix fresh-meat vegetables\">\n"; 
echo "                    <div class=\"featured__item\">\n"; 
echo "                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-5.jpg\">\n"; 
echo "                            <ul class=\"featured__item__pic__hover\">\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\n"; 
echo "                            </ul>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"featured__item__text\">\n"; 
echo "                            <h6><a href=\"#\">Crab Pool Security</a></h6>\n"; 
echo "                            <h5>Rp35.000</h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-3 col-md-4 col-sm-6 mix oranges fastfood\">\n"; 
echo "                    <div class=\"featured__item\">\n"; 
echo "                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-6.jpg\">\n"; 
echo "                            <ul class=\"featured__item__pic__hover\">\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\n"; 
echo "                            </ul>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"featured__item__text\">\n"; 
echo "                            <h6><a href=\"#\">Crab Pool Security</a></h6>\n"; 
echo "                            <h5>Rp35.000</h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-3 col-md-4 col-sm-6 mix fresh-meat vegetables\">\n"; 
echo "                    <div class=\"featured__item\">\n"; 
echo "                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-7.jpg\">\n"; 
echo "                            <ul class=\"featured__item__pic__hover\">\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\n"; 
echo "                            </ul>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"featured__item__text\">\n"; 
echo "                            <h6><a href=\"#\">Crab Pool Security</a></h6>\n"; 
echo "                            <h5>Rp35.000</h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-3 col-md-4 col-sm-6 mix fastfood vegetables\">\n"; 
echo "                    <div class=\"featured__item\">\n"; 
echo "                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-8.jpg\">\n"; 
echo "                            <ul class=\"featured__item__pic__hover\">\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\n"; 
echo "                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\n"; 
echo "                            </ul>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"featured__item__text\">\n"; 
echo "                            <h6><a href=\"#\">Crab Pool Security</a></h6>\n"; 
echo "                            <h5>Rp35.000</h5>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </section>\n"; 
echo "    <!-- Featured Section End -->\n"; 
echo "\n"; 
echo "    <!-- Banner Begin -->\n"; 
echo "    <div class=\"banner\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-6 col-md-6 col-sm-6\">\n"; 
echo "                    <div class=\"banner__pic\">\n"; 
echo "                        <img src=\"img/banner/banner-1.jpg\" alt=\"\">\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-6 col-md-6 col-sm-6\">\n"; 
echo "                    <div class=\"banner__pic\">\n"; 
echo "                        <img src=\"img/banner/banner-2.jpg\" alt=\"\">\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!-- Banner End -->\n"; 
echo "\n"; 
echo "    <!-- Blog Section Begin -->\n"; 
echo "    <section class=\"from-blog spad\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-12\">\n"; 
echo "                    <div class=\"section-title from-blog__title\">\n"; 
echo "                        <h2>From The Articles</h2>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-4 col-md-4 col-sm-6\">\n"; 
echo "                    <div class=\"blog__item\">\n"; 
echo "                        <div class=\"blog__item__pic\">\n"; 
echo "                            <img src=\"img/blog/blog-1.jpg\" alt=\"\">\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"blog__item__text\">\n"; 
echo "                            <ul>\n"; 
echo "                                <li><i class=\"fa fa-calendar-o\"></i> May 4,2019</li>\n"; 
echo "                                <li><i class=\"fa fa-comment-o\"></i> 5</li>\n"; 
echo "                            </ul>\n"; 
echo "                            <h5><a href=\"#\">Cooking tips make cooking simple</a></h5>\n"; 
echo "                            <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-4 col-md-4 col-sm-6\">\n"; 
echo "                    <div class=\"blog__item\">\n"; 
echo "                        <div class=\"blog__item__pic\">\n"; 
echo "                            <img src=\"img/blog/blog-2.jpg\" alt=\"\">\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"blog__item__text\">\n"; 
echo "                            <ul>\n"; 
echo "                                <li><i class=\"fa fa-calendar-o\"></i> May 4,2019</li>\n"; 
echo "                                <li><i class=\"fa fa-comment-o\"></i> 5</li>\n"; 
echo "                            </ul>\n"; 
echo "                            <h5><a href=\"#\">6 ways to prepare breakfast for 30</a></h5>\n"; 
echo "                            <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-4 col-md-4 col-sm-6\">\n"; 
echo "                    <div class=\"blog__item\">\n"; 
echo "                        <div class=\"blog__item__pic\">\n"; 
echo "                            <img src=\"img/blog/blog-3.jpg\" alt=\"\">\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"blog__item__text\">\n"; 
echo "                            <ul>\n"; 
echo "                                <li><i class=\"fa fa-calendar-o\"></i> May 4,2019</li>\n"; 
echo "                                <li><i class=\"fa fa-comment-o\"></i> 5</li>\n"; 
echo "                            </ul>\n"; 
echo "                            <h5><a href=\"#\">Visit the clean farm in the US</a></h5>\n"; 
echo "                            <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </section>\n"; 
echo "    <!-- Blog Section End -->\n"; 
echo "\n"; 
echo "    <!-- Footer Section Begin -->\n"; 
echo "    <footer class=\"footer spad\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-3 col-md-6 col-sm-6\">\n"; 
echo "                    <div class=\"footer__about\">\n"; 
echo "                        <div class=\"footer__about__logo\">\n"; 
echo "                            <a href=\"./index.html\"><img src=\"img/logo.png\" alt=\"\"></a>\n"; 
echo "                        </div>\n"; 
echo "                        <ul>\n"; 
echo "                            <li>Address: Jl. Tirto Utomo No:8 Gg:12 Landungsari Malang</li>\n"; 
echo "                            <li>Phone: +62 878 4207-7793</li>\n"; 
echo "                            <li>Email:DPirates@gmail.com</li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-4 col-md-6 col-sm-6 offset-lg-1\">\n"; 
echo "                    <div class=\"footer__widget\">\n"; 
echo "                      \n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-lg-4 col-md-12\">\n"; 
echo "                    <div class=\"footer__widget\">\n"; 
echo "                        <h6>Join Our Newsletter Now</h6>\n"; 
echo "                        <p>Get E-mail updates about our latest shop and special offers.</p>\n"; 
echo "                        <form action=\"#\">\n"; 
echo "                            <input type=\"text\" placeholder=\"Enter your mail\">\n"; 
echo "                            <button type=\"submit\" class=\"site-btn\">Subscribe</button>\n"; 
echo "                        </form>\n"; 
echo "                        <div class=\"footer__widget__social\">\n"; 
echo "                            <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n"; 
echo "                            <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n"; 
echo "                            <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n"; 
echo "                            <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-12\">\n"; 
echo "                    <div class=\"footer__copyright\">\n"; 
echo "                        <div class=\"footer__copyright__text\"><p>\n"; 
echo "  Copyright 2021 By DPirates All rights reserved\n"; 
echo " </p></div>\n"; 
echo "                        <div class=\"footer__copyright__payment\"><img src=\"img/payment-item.png\" alt=\"\"></div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </footer>\n"; 
echo "    <!-- Footer Section End -->\n"; 
echo "\n"; 
echo "    <!-- Js Plugins -->\n"; 
echo "    <script src=\"js/jquery-3.3.1.min.js\"></script>\n"; 
echo "    <script src=\"js/bootstrap.min.js\"></script>\n"; 
echo "    <script src=\"js/jquery.nice-select.min.js\"></script>\n"; 
echo "    <script src=\"js/jquery-ui.min.js\"></script>\n"; 
echo "    <script src=\"js/jquery.slicknav.js\"></script>\n"; 
echo "    <script src=\"js/mixitup.min.js\"></script>\n"; 
echo "    <script src=\"js/owl.carousel.min.js\"></script>\n"; 
echo "    <script src=\"js/main.js\"></script>\n"; 
echo "</body>\n"; 
echo "\n";
?>